# Generated by Django 4.1.7 on 2023-06-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_praceid"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="PraceID",),
    ]
