# Generated by Django 4.1.7 on 2023-06-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_remove_anime_animeimage"),
        ("post", "0005_post_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="AnimeID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animeid",
                to="anime.anime",
            ),
            preserve_default=False,
        ),
    ]
