# Generated by Django 4.1.7 on 2023-06-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "amineid",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=200)),
                ("related", models.CharField(max_length=200)),
                ("animeimage", models.ImageField(upload_to="")),
            ],
        ),
    ]
