# Generated by Django 4.1.7 on 2023-06-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="anime", name="animeimage",),
    ]
