# Generated by Django 4.1.7 on 2023-06-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0005_alter_customer_name"),
        ("anime", "0002_remove_anime_animeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="gmap.customer",
                to_field="name",
            ),
            preserve_default=False,
        ),
    ]
