# Generated by Django 4.1.7 on 2023-06-22 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0005_alter_customer_name"),
        ("anime", "0003_anime_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="anime", name="name",),
        migrations.AddField(
            model_name="anime",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animes",
                to="gmap.customer",
            ),
            preserve_default=False,
        ),
    ]
