# Generated by Django 4.1.7 on 2023-06-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_remove_anime_customer_anime_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="anime", name="name",),
    ]
