# Generated by Django 4.1.7 on 2023-06-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "PraceID",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="場所ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名前")),
                ("address", models.CharField(max_length=50, verbose_name="住所")),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="緯度"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="経度"
                    ),
                ),
            ],
            options={"verbose_name": "顧客", "verbose_name_plural": "顧客",},
        ),
    ]
