# Generated by Django 4.1.7 on 2023-06-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="PraceID", new_name="ID",
        ),
    ]
