# Generated by Django 4.1.7 on 2023-06-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0002_rename_praceid_customer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="ID", new_name="PraceID",
        ),
    ]
