# Generated by Django 4.1.7 on 2023-06-20 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
        ("gmap", "0003_rename_id_customer_praceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="animeid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anime",
                to="anime.anime",
            ),
            preserve_default=False,
        ),
    ]
