# Generated by Django 4.1.7 on 2023-06-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0004_customer_animeid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="名前"),
        ),
    ]
