# Generated by Django 4.1.7 on 2023-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmap", "0005_alter_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                default=1, upload_to="customer_images/", verbose_name="画像"
            ),
            preserve_default=False,
        ),
    ]
